# .github/workflows/caller-workflow.yml
name: Shared IOS build/test/deploy Workflow

permissions:
      contents: write
      pull-requests: write

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-reusable-workflow:
    uses: jamesmittlerii/workflows/.github/workflows/ios.yml@main # Or a specific commit SHA or tag
    secrets: inherit

